### ISSUE TITLE
Problem with Studio

### ISSUE THREAD

**Issue by dalareo** [OpenSaasAU/edx-docker-ansible#3]
Everything seems nice but when I try to save a course in Studio or go to its URL I get:

Studio's having trouble saving your work

This may be happening because of an error with our server or your internet connection. Try refreshing the page or making sure you are online.

NGINX throws: 

2016/12/30 23:02:28 [error] 9#9: *73 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: ~^((stage|prod)-)?studio.*, request: "GET /home/ HTTP/1.1", upstream: "http://172.17.0.10:8010/home/", host: "studio.edx.opensaas.local:18010"

I guess is a problem with network, but container IP is not suposed to be accesible from host.

**Comment by borisno2** [comment]
@dalareo glad it built OK for you.. sounds like a backend error with rabbit or something else.. could you run `tail -f /var/log/syslog` on the host machine, or whatever your log destination is on the host? OpenEdx apps logs to the syslog of the local machine and due to docker not doing syslog, i have had to map the /dev/log volume on the container to /dev/log of the host, so all the logs for the Edx application show up in the logs of the host.

So this should give you more info for what is going on.. My guess is the celery (rabbitmq password is incorrect), my bad, the celery password is 'password' in edxapp_vars.yml.sample but 'celery' in container_vars.yml..

Let me know what you come up with...

**Comment by dalareo** [comment]
It did the trick!!

I feel totally dumb dealing with Open edX... a lot of different technologies put together!! Happy new year!!

**Comment by dalareo** [comment]
Hi @borisno2 is it neccessary to hack something to make studio.* redirect to EDXAPP_CMS_NGINX_PORT ? I still need to set port manually in address bar when accesing to Studio but cms file at sites-available seem to be right!

**Comment by borisno2** [comment]
@dalareo, currently the nginx deploy is identical to the standard openedx installation, which configures different port numbers on nginx for each service. Is order to make studio for on a standard port nginx would need to be configured to use hostnames instead of port numbers. I have just been using the Rancher LB to do the redirecting based on hostnames. If you need a hand feel free to ping me on slack or shoot me an email.
